services:
  tmpoints:
    image: tmpoints
    environment:
      - 'APP_URL='
      - 'SECURITY_KEY='
      - 'WS_NAME='
      - 'WS_PASS='
    volumes:
      - ./certs:/certificates/
    ports:
      - 8123:8080

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=points'
      - 'POSTGRES_PASSWORD=points'
      - 'POSTGRES_USER=points'
      - 'PGDATA=/data/postgres'
    volumes:
      - ./db:/data/postgres
    ports:
      - '5432'
